#!/bin/sh
#
# Starts httpd.
#

# Allow a few customizations from a config file
test -r /etc/default/httpd && . /etc/default/httpd

start() {
	printf "Starting httpd: "
	umask 077

	start-stop-daemon -S -q -b --exec /usr/bin/php -- -S 0.0.0.0:80 -t /var/www/public
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping httpd: "
	kill -9 `pidof php`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
